"""initial schema

Revision ID: 1fe7b52e9129
Revises: 
Create Date: 2026-08-25 21:53:37.729945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe7b52e9129'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dietary_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('cuisine_type', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cuisine_type IN ('North Indian', 'South Indian', 'Chinese', 'Indo-Chinese', 'Italian', 'Continental', 'Fast Food', 'American', 'Beverages', 'Desserts', 'Other') OR cuisine_type IS NULL", name='ck_restaurant_valid_cuisine'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('default_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(role = 'PLATFORM_ADMIN' AND restaurant_id IS NULL) OR (role = 'RESTAURANT_ADMIN' AND restaurant_id IS NOT NULL)", name='ck_admin_scope'),
    sa.CheckConstraint("role IN ('PLATFORM_ADMIN', 'RESTAURANT_ADMIN')", name='ck_admin_valid_role'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_admin_restaurant', 'admin_users', ['restaurant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('restaurant_id', sa.String(length=36), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_cart', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_user', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_veg', sa.Boolean(), nullable=False),
    sa.Column('spice_level', sa.String(length=20), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=False),
    sa.Column('serving_size', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('Starter', 'Main Course', 'Bread', 'Rice', 'Beverage', 'Dessert', 'Side', 'Combo', 'Fast Food')", name='ck_menu_items_valid_category'),
    sa.CheckConstraint("cuisine IN ('North Indian', 'South Indian', 'Chinese', 'Indo-Chinese', 'Italian', 'Continental', 'Fast Food', 'American', 'Beverages', 'Desserts', 'Other')", name='ck_menu_items_valid_cuisine'),
    sa.CheckConstraint("spice_level IN ('None', 'Low', 'Medium', 'High', 'Extreme')", name='ck_menu_items_valid_spice'),
    sa.CheckConstraint('price >= 0', name='ck_menu_items_price_nonneg'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_menu_items_rating_range'),
    sa.CheckConstraint('serving_size > 0', name='ck_menu_items_serving_positive'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_category', 'menu_items', ['category'], unique=False)
    op.create_index('idx_menu_cuisine', 'menu_items', ['cuisine'], unique=False)
    op.create_index('idx_menu_filter', 'menu_items', ['restaurant_id', 'is_available', 'is_veg', 'spice_level', 'price'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('constraints_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled')", name='ck_order_valid_status'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user', 'orders', ['user_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('menu_item_allergens',
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'allergen_id')
    )
    op.create_table('menu_item_tags',
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['dietary_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'tag_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('menu_item_tags')
    op.drop_table('menu_item_allergens')
    op.drop_index('idx_orders_user', table_name='orders', postgresql_using='btree')
    op.drop_table('orders')
    op.drop_index('idx_menu_filter', table_name='menu_items')
    op.drop_index('idx_menu_cuisine', table_name='menu_items')
    op.drop_index('idx_menu_category', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('idx_conversations_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_admin_restaurant', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('users')
    op.drop_table('restaurants')
    op.drop_table('dietary_tags')
    op.drop_table('allergens')
    # ### end Alembic commands ###
