"""add_conversation_status

Revision ID: 8b842829355b
Revises: 7bf3017e50b7
Create Date: 2026-08-29 11:55:18.619332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b842829355b'
down_revision: Union[str, None] = '7bf3017e50b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'status')
    # ### end Alembic commands ###
