"""add_ingredients

Revision ID: a5ecc734897f
Revises: 1fe7b52e9129
Create Date: 2026-08-26 08:27:01.199291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ecc734897f'
down_revision: Union[str, None] = '1fe7b52e9129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_allergens',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingredient_id', 'allergen_id')
    )
    op.create_table('menu_item_ingredients',
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'ingredient_id')
    )
    op.drop_table('menu_item_allergens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_allergens',
    sa.Column('menu_item_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('allergen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name='menu_item_allergens_allergen_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='menu_item_allergens_menu_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'allergen_id', name='menu_item_allergens_pkey')
    )
    op.drop_table('menu_item_ingredients')
    op.drop_table('ingredient_allergens')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
