"""sync_dietary_preference

Revision ID: e7be1516756d
Revises: 8b842829355b
Create Date: 2026-08-29 21:25:12.705970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7be1516756d'
down_revision: Union[str, None] = '8b842829355b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('dietary_preference', sa.String(length=30), nullable=False, server_default='Vegetarian'))
    op.drop_index('idx_menu_filter', table_name='menu_items')
    op.create_index('idx_menu_filter', 'menu_items', ['restaurant_id', 'is_available', 'dietary_preference', 'spice_level', 'price'], unique=False)
    op.drop_column('menu_items', 'is_veg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_veg', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('idx_menu_filter', table_name='menu_items')
    op.create_index('idx_menu_filter', 'menu_items', ['restaurant_id', 'is_available', 'is_veg', 'spice_level', 'price'], unique=False)
    op.drop_column('menu_items', 'dietary_preference')
    # ### end Alembic commands ###
